.\"    Copyright 2015 by Clemson University
.\"
.\"    This file is part of snmpiostat.
.\"
.\"    Snmpiostat is free software: you can redistribute it and/or modify
.\"    it under the terms of the Lesser GNU General Public License as published by
.\"    the Free Software Foundation, either version 3 of the License, or
.\"    (at your option) any later version.
.\"
.\"    snmpiostat is distributed in the hope that it will be useful,
.\"    but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"    Lesser GNU General Public License for more details.
.\"
.\"    You should have received a copy of the Lesser GNU General Public License
.\"    along with snmpiostat.  If not, see <http://www.gnu.org/licenses/>.
.TH snmpiostatagent 8 "11 Jun 2015"
.SH NAME
snmpiostatagent - SNMP agent to make device I/O data used by iostat available to SNMP clients
.SH SYNOPSIS
.B snmpiostatagent
.SH DESCRIPTION
.B snmpiostatagent
is a ucd-snmp/pass or ucd-snmp/pass_persist module that makes the raw device I/O data used by
iostat(1) available to SNMP clients.  A companion program
.B snmpiostat(1)
uses this data to implement a version of iostat(1) that uses SNMP to retrieve device I/O data
from a remote host.
.LP
A description of the MIB can be found in DEVIOSTAT.MIB.  This can be added to the MIBs known
by SNMP management tools (eg UCD's net-snmp package) which can then monitor this data as needed.
.LP
.B snmpiostatagent
can operate as either a "pass" or "pass_persist" module.  "pass_persist" is recommended as
there is less overhead starting and stopping it for each request.  To configure snmpd(8) to
pass DEVIOSTAT.MIB OIDs to this module add a line to
.I /etc/snmp/snmpd.conf
like this:
.LP
.nf
  pass_persist .1.3.6.1.3.2 /usr/local/sbin/snmpiostatagent
.fi
.LP
Then restart or reload snmpd(8):
.LP
.nf
  service snmpd restart (or reload)
.fi
.SH CONFIGURATION
The configuration file
.I snmpiostat.conf
is installed in
.I /usr/local/etc
by default.  The following options may be configured:
.TP
.I baseoid ...
The OID under which all the OIDs defined in DEVIOSTAT.MIB are found.  The default is
SNMPv2-SMI::experimental.2 (.1.3.6.1.3.2).  If you change this value you will also
need to update DEVIOSTAT.MIB (if you plan to add this MIB to your SNMP management tool),
and you must make sure that
.B snmpiostat(1)
also is configured with the same baseoid.
.B snmpiostat(1)
uses the same config file as
.B snmpiostatagent(8).
.TP
.I debug 0|1
Set to 1 to enable debugging, default is 0.  If run from the command line debug messages are written to stdout,
if started by snmpd(8) then they are written to syslog.
.TP
.I syslogfacility daemon|local0-7|user
Set syslog facility, the default is "daemon".
.SH SEE ALSO
snmpiostat(1), snmpd(8), iostat(1)
.SH AUTHOR
Bob Schwartzkopf,
Clemson University
